[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['echo "Build complete - ready for deployment"']

[start]
cmd = 'npm run once'